### ISSUE TITLE
Site Support Requested - https://thescene.com

### ISSUE THREAD

**Issue by darinh** [emilianobovetti/FuckFuckAdBlock#2]
### Steps to reproduce
- Navigate to [the scene](https://thescene.com).
- Click on any video in the carousel at the top of the page
### Expected result
- You are navigated away to a video player.
- The video plays
### Actual result
- You are navigated away to a video player
- In place of the video, a message is displayed: _"Please disable your ad blocker -- If we can't show an ad, we can't show content. Please whitelist us so we can keep bringing you great videos for free"_

**Comment by emilianobovetti** [comment]
I tried to fix this in the current release, it seems to me now works properly. Thanks for your help : )

**Comment by darinh** [comment]
Yep.  Looks good.  Thanks!
