### ISSUE TITLE
Site request: CBS.com

### ISSUE THREAD

**Issue by kamakazikamikaze** [emilianobovetti/FuckFuckAdBlock#3]
CBS.com is still able to detect uBlock Origin even with FuckFuckAdBlock installed.

[Direct URL](http://www.cbs.com/shows/ncis-new-orleans/video/).

<img width="830" alt="screen shot 2015-12-22 at 9 17 23 am" src="https://cloud.githubusercontent.com/assets/8862823/11958357/1886b1c4-a88d-11e5-9ae1-7da9be1450c9.PNG">

**Comment by emilianobovetti** [comment]
I can't find the way they detect AdBlock, I'm afraid they still use Flash for this. In that case I'm not able to fix

**Comment by kamakazikamikaze** [comment]
That sucks. Thanks for looking into it though!

**Comment by emilianobovetti** [comment]
FuckFuckAdBlock 0.4 will allow you to surf on cbs.com
