### ISSUE TITLE
Doesn't work on Forbes

### ISSUE THREAD

**Issue by andreis** [emilianobovetti/FuckFuckAdBlock#4]
http://www.forbes.com/forbes/welcome/

**Comment by emilianobovetti** [comment]
It works injecting something like

``` javascript
fbs_settings = { classes: "e30=" }
```

Unfortunately I'm afraid this will compromise some other site features. 
[EDIT] I will update FFAdBlock, please let me know of you find bugs while browsing on forbes.com

**Comment by emilianobovetti** [comment]
Version 0.1.2 should do the trick
