### ISSUE TITLE
"...could not be installed because it appears to be corrupt"

### ISSUE THREAD

**Issue by ghost** [emilianobovetti/FuckFuckAdBlock#8]
As of Saturday 2016-05-07 at 1:10 PM PDT, IF I go to the addon's page at https://addons.mozilla.org/en-US/firefox/addon/fuckfuckadblock/, AND I click Add to Firefox, THEN i receive the popup message, "The add-on downloaded from addons.mozilla.org could not be installed because it appears to be corrupt".

**Comment by emilianobovetti** [comment]
I've just tried and it seems to work fine

![FuckFuckAdBlock installed successfully](https://cloud.githubusercontent.com/assets/3957026/15094387/8223fcdc-14a2-11e6-88b5-141d64bd7c95.jpg)

anyway this issue is related to addons.mozilla.org, not to FFAdBlock

**Comment by ghost** [comment]
Well it's still definitely not working for me. I even tried downloading the XPI file and installing from disk. Same message. This isn't a show stopper for me but just making you aware...

**Comment by emilianobovetti** [comment]
I don't know how to help, you could try to clone the project and launch _build.sh_ script, then install _firefox.xpi_ file inside the _build_ directory, or you could [download this xpi](https://mega.nz/#!EU10mbBA!ieh6vOGKsEZYr-UqOiGNnwOZc5W2_trHq6LbPyB4n5U)
